### ISSUE TITLE
Frontend 2.0 Backlog

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/frontend#2]
### Tasks

- 建立工廠
    - 手機版 #1
        - [x] 顯示設定手機版按鈕 component 化
        - [x] 顯示經緯度手機版
        - [x] 新增工廠成功 modal
    - 電腦  #8 
        - 桌面版 navigation bar
            - [x] 三步驟顯示
            - [x] 取消新增工廠按鈕
        - 經緯度
            - [x] 搜尋經緯度表單
            - [x] 打開/關閉經緯度介面
- 檢視工廠
    - 手機版
        - [x] 工廠詳細資料 Bottom Sheet #9 
            - [x] 詳細資料半開/全開切換
            - [x] 詳細資料顯示
        - [x] 工廠篩選按鈕（navbar 下面那排 @Yukaii
        - [x] 顯示設定按鈕
        - ~~詳細資料顯示時隱藏篩選按鈕、顯示設定~~
        - [x] 分享按鈕 #14 
            - [x] 點擊分享按鈕複製連結
            - [x] 顯示通知
    - 電腦版
        - [ ] 電腦版顯示設定按鈕 popover menu
        - [x] 工廠詳細資料 Sidebar #15 
        - [x] 工廠詳細資料 Sidebar 收合 #15
        - [x] 分享按鈕已複製提示 #15 
- 補充工廠
    - 手機版 #16
        - [x] 補充照片按鈕
        - [x] 上傳圖片表單串接
        - [x] 補充描述按鈕
        - [x] 補充描述表單串接
        - [x] 補充工廠成功 modal
    - 電腦版 #19
        - [x] 補充描述 modal
